import { expect, test } from '@playwright/test';
import { createVerifiedUser, resetAuthEmulator, resetDatabaseEmulator, seedDatabaseEmulator } from '../helpers/auth-emulator.js';
import { captureUi } from '../helpers/ui-review.js';

const password = 'SiviEntrada2026';
async function login(page, email) {
  await page.goto('/?authEmulator=1#/acesso?modo=login');
  await expect(page.locator('.auth-shell')).toHaveAttribute('data-ui-ready', 'true');
  await page.locator('#login-email').fill(email);
  await page.locator('#login-password').fill(password);
  await page.locator('#login-form button[type="submit"]').click();
  await page.waitForURL(/#\/app\//);
}
async function fillApplication(page, name = 'Indústria Entrada') {
  const form = page.locator('[data-create-organization]');
  await form.getByLabel('Nome da empresa').fill(name);
  await form.getByLabel('CNPJ', { exact: true }).fill('12.345.678/0001-90');
  await form.getByLabel('Cidade', { exact: true }).fill('Campinas');
  await form.getByLabel('UF', { exact: true }).selectOption('SP');
  await form.getByLabel('Telefone ou e-mail de contato').fill('compras@entrada.test');
  await form.getByLabel('Compradora', { exact: true }).check();
  await form.getByRole('button', { name: 'Revisar cadastro' }).click();
}
test('public entry, correction, resubmission, approval and refusal persist across sessions', async ({ browser, page }) => {
  test.setTimeout(180000);
  page.setDefaultTimeout(15000);
  await resetAuthEmulator(); await resetDatabaseEmulator();
  const owner = await createVerifiedUser({ email: 'entrada@sivi.test', password, displayName: 'Responsável' });
  const admin = await createVerifiedUser({ email: 'entrada-admin@sivi.test', password, displayName: 'Admin' });
  await seedDatabaseEmulator(`platformAdmins/${admin.uid}`, true);
  await page.goto('/?authEmulator=1');
  await expect(page.getByRole('heading', { name: /Sua próxima compra industrial/ })).toBeVisible();
  await captureUi(page, 'pagina-publica');
  await page.getByRole('link', { name: 'Cadastrar empresa', exact: true }).first().click();
  await expect(page.locator('.auth-shell')).toHaveAttribute('data-mode', 'register');
  await login(page, owner.email);
  await captureUi(page, 'cadastro-empresa');
  await fillApplication(page);
  await captureUi(page, 'revisao-cadastro');
  await page.getByRole('button', { name: 'Voltar e editar' }).click();
  await expect(page.getByLabel('Cidade', { exact: true })).toHaveValue('Campinas');
  await page.getByRole('button', { name: 'Revisar cadastro' }).click();
  await page.getByRole('button', { name: 'Solicitar acesso', exact: true }).click();
  const company = page.locator('.context-company', { hasText: 'Indústria Entrada' });
  await expect(company).toContainText('Em análise');
  await expect(company.getByRole('button', { name: /Entrar como/ })).toHaveCount(0);
  await captureUi(page, 'cadastro-em-analise');
  const adminContext = await browser.newContext();
  const adminPage = await adminContext.newPage();
  try {
    await login(adminPage, admin.email);
    await adminPage.getByRole('button', { name: /Abrir portal administrativo/ }).click();
    const review = adminPage.locator('.admin-organization-card', { hasText: 'Indústria Entrada' });
    await expect(review).toContainText('Campinas/SP');
    await company.getByRole('button', { name: 'Consultar cadastro' }).click();
    await page.getByRole('button', { name: 'Editar cadastro' }).click();
    await page.getByLabel('Telefone ou e-mail de contato').fill('compras-novo@entrada.test');
    await page.getByRole('button', { name: 'Revisar cadastro' }).click();
    await page.getByRole('button', { name: 'Corrigir e reenviar' }).click();
    await expect(company).toContainText('Em análise');
    await review.getByRole('button', { name: 'Aprovar', exact: true }).click();
    await expect(adminPage.locator('[data-admin-feedback]')).toContainText('cadastro mudou');
    await adminPage.getByRole('button', { name: 'Atualizar solicitações' }).click();
    await expect(review).toContainText('compras-novo@entrada.test');
    await review.getByRole('button', { name: 'Solicitar correção' }).click();
    await expect(adminPage.locator('[data-admin-feedback]')).toContainText('Informe o motivo');
    await review.getByLabel('Motivo para Indústria Entrada').fill('Confirme o telefone de contato.');
    await review.getByRole('button', { name: 'Solicitar correção' }).click();
    await expect(review).toContainText('Correção solicitada');
    await page.getByRole('button', { name: 'Atualizar situação' }).click();
    await expect(company).toContainText('Correção solicitada');
    await company.getByRole('button', { name: 'Consultar cadastro' }).click();
    await expect(page.locator('.application-detail')).toContainText('Confirme o telefone de contato.');
    await captureUi(page, 'correcao-solicitada');
    await page.getByRole('button', { name: 'Corrigir e reenviar' }).click();
    await expect(page.getByLabel('Nome da empresa')).toHaveValue('Indústria Entrada');
    await page.getByLabel('Telefone ou e-mail de contato').fill('(11) 99999-4321');
    await page.getByRole('button', { name: 'Revisar cadastro' }).click();
    await page.getByRole('button', { name: 'Corrigir e reenviar' }).click();
    await expect(company).toContainText('Em análise');
    await adminPage.getByRole('button', { name: 'Atualizar solicitações' }).click();
    await expect(review).toContainText('(11) 99999-4321');
    await captureUi(adminPage, 'analise-administrativa');
    await review.getByRole('button', { name: 'Aprovar', exact: true }).click();
    await expect(review).toContainText('Ativa');
    await page.getByRole('button', { name: 'Atualizar situação' }).click();
    await expect(company).toContainText('Empresa ativa');
    await page.getByRole('button', { name: /Entrar como comprador/ }).click();
    await expect(page.getByRole('link', { name: 'Criar primeira demanda' })).toBeVisible();
    await page.locator('[data-account-menu] summary').click(); await page.locator('[data-logout]').click();
    await login(page, owner.email);
    await expect(page).toHaveURL(/#\/app\/comprador\/inicio$/);
    await page.getByRole('button', { name: 'Trocar empresa', exact: true }).first().click();
    await page.getByRole('button', { name: 'Cadastrar empresa', exact: true }).click();
    await fillApplication(page, 'Cadastro Recusado');
    await page.getByRole('button', { name: 'Solicitar acesso', exact: true }).click();
    await expect(page.locator('.context-company', { hasText: 'Cadastro Recusado' })).toContainText('Em análise');
    await adminPage.getByRole('button', { name: 'Atualizar solicitações' }).click();
    const refused = adminPage.locator('.admin-organization-card', { hasText: 'Cadastro Recusado' });
    await refused.getByLabel('Motivo para Cadastro Recusado').fill('Cadastro duplicado. Utilize a empresa já aprovada.');
    await refused.getByRole('button', { name: 'Recusar cadastro' }).click();
    await expect(refused).toHaveAttribute('data-status', 'rejected');
    await page.getByRole('button', { name: 'Atualizar situação' }).click();
    const denied = page.locator('.context-company', { hasText: 'Cadastro Recusado' });
    await expect(denied).toHaveAttribute('data-status', 'rejected');
    await denied.getByRole('button', { name: 'Consultar cadastro' }).click();
    await expect(page.locator('.application-detail')).toContainText('Cadastro duplicado');
    await expect(page.getByRole('button', { name: 'Corrigir e reenviar' })).toHaveCount(0);
    await page.locator('[data-account-menu] summary').click(); await page.locator('[data-logout]').click();
    await login(page, owner.email);
    await expect(page).toHaveURL(/#\/app\/comprador\/inicio$/);
  } finally { await adminContext.close(); }
});
